name: Check & test & build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort pytest
          pip install -r test_requirements.txt
      - name: Run black check
        run: |
          black coinpaprika tests --check
      - name: Run isort check
        run: |
          isort coinpaprika tests --check
      - name: Test with pytest
        run: |
          pytest tests/test_api_request.py -v